apiVersion: v1
kind: PersistentVolume
metadata:
  name: pv-vol2
spec:
  storageClassName: standard
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: nfs01
    path: "/html"
