apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pv-vol2
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  volumeName: "pv-vol2"
  storageClassName: standard
